version: '3.6'

services:
  rk22-test:
    ports:
      - '3000:3000'
    user: node
    env_file:
      - .env.production
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /app
    volumes:
      - /app
    command: sh -c "node .output/server/index.mjs"
    stdin_open: true
    restart: always
    tty: true
    networks:
      - default
